# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatever', '0002_auto_20171009_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
    ]
